SELECT 
9 bpk_id,order_item_id,verify_date,verify_time,hn,vn,visit_id,visit_spid,visit_date,visit_time,fix_visit_type_id,base_patient_type_id,financial_discharge,financial_discharge_date,financial_discharge_time,main_doctor_id,patient_name,base_billing_group_id,billing_description,account_id,account_description,item_id,item_description,verify_eid,overify_spid,oordered_by_service_point,overify_deptid,oordered_by_department,verify_spid,ordered_by_service_point,verify_deptid,ordered_by_department,pverify_spid,pordered_by_service_point,pverify_deptid,pordered_by_department,execute_date,execute_time,execute_eid,execute_spid,execute_by_service_point,execute_deptid,execute_by_department,fix_order_status_id,order_status_description,fix_item_type_id,quantity,base_unit_id,unit_price_cost,unit_price_sale,linecost,linesale,wlinediscount,wlinepaid,an
FROM 
bpk_account_credit_detail 
WHERE verify_date='$P{FromDate}'
