/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmConvertDocScan.java
 *
 * Created on Jan 25, 2016, 6:18:22 PM
 */
package com.bpk.app.emrapp;

import com.bpk.core.emrcore.dao.DocScanDAOFactory;
import com.bpk.core.emrcore.dao.DocScanDAO;
import com.bpk.persistence.emrdto.BpkDocumentScanVO;
import com.bpk.persistence.emrdto.FolderVO;
import com.bpk.persistence.emrdto.PatientVO;
import com.bpk.persistence.emrdto.VisitVO;
import com.bpk.utility.EventNames;
import com.bpk.utility.MyString;
import com.bpk.utility.Utility;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import javax.swing.Timer;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author SURACHAI.TO
 */
public class FrmImageScan extends javax.swing.JFrame
{

    private PatientVO patientVO = null;

    Thread aThread = null;
    Timer aTimer = null;

    /** Creates new form FrmConvertDocScan */
    public FrmImageScan()
    {
        try
        {
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new Theme());
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.Font aFont = new java.awt.Font("Tahoma", 0, 14);
            UIManager.put("OptionPane.font", aFont);
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        aPanelTop = new javax.swing.JPanel();
        aBtnStartScan = new javax.swing.JButton();
        aBtnCancel = new javax.swing.JButton();
        aPnlBody = new javax.swing.JPanel();
        separator1 = new javax.swing.JSeparator();
        aLblTotalScan = new javax.swing.JLabel();
        aTxtTotalScan = new javax.swing.JTextField();
        aLblTotalMatched = new javax.swing.JLabel();
        aTxtTotalMatched = new javax.swing.JTextField();
        aLblTotalMatchedPageUnit = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        aLblHn = new javax.swing.JLabel();
        aTxtHn = new javax.swing.JTextField();
        aTxtPatientName = new javax.swing.JTextField();
        aLblProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Scan");
        setResizable(false);

        aPanelTop.setLayout(new java.awt.GridBagLayout());

        aBtnStartScan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aBtnStartScan.setLabel("Start Scan");
        aBtnStartScan.setMargin(new java.awt.Insets(0, 0, 0, 0));
        aBtnStartScan.setMaximumSize(new java.awt.Dimension(80, 24));
        aBtnStartScan.setMinimumSize(new java.awt.Dimension(80, 24));
        aBtnStartScan.setPreferredSize(new java.awt.Dimension(80, 24));
        aBtnStartScan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBtnStartScanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 11, 0);
        aPanelTop.add(aBtnStartScan, gridBagConstraints);

        aBtnCancel.setFont(new java.awt.Font("Tahoma", 1, 12));
        aBtnCancel.setEnabled(false);
        aBtnCancel.setLabel("Cancel");
        aBtnCancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        aBtnCancel.setMaximumSize(new java.awt.Dimension(80, 24));
        aBtnCancel.setMinimumSize(new java.awt.Dimension(80, 24));
        aBtnCancel.setPreferredSize(new java.awt.Dimension(80, 24));
        aBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBtnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 11, 11);
        aPanelTop.add(aBtnCancel, gridBagConstraints);

        getContentPane().add(aPanelTop, java.awt.BorderLayout.PAGE_START);

        aPnlBody.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 1);
        aPnlBody.add(separator1, gridBagConstraints);

        aLblTotalScan.setFont(new java.awt.Font("Tahoma", 0, 12));
        aLblTotalScan.setText("Scanned:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlBody.add(aLblTotalScan, gridBagConstraints);

        aTxtTotalScan.setEditable(false);
        aTxtTotalScan.setFont(new java.awt.Font("Tahoma", 0, 12));
        aTxtTotalScan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aTxtTotalScan.setMinimumSize(new java.awt.Dimension(60, 24));
        aTxtTotalScan.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 0);
        aPnlBody.add(aTxtTotalScan, gridBagConstraints);

        aLblTotalScanPageUnit.setFont(new java.awt.Font("Tahoma", 0, 12));
        aLblTotalScanPageUnit.setText("pages");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 11);
        aPnlBody.add(aLblTotalScanPageUnit, gridBagConstraints);

        aLblTotalMatched.setFont(new java.awt.Font("Tahoma", 0, 12));
        aLblTotalMatched.setText("Matched:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
        aPnlBody.add(aLblTotalMatched, gridBagConstraints);

        aTxtTotalMatched.setEditable(false);
        aTxtTotalMatched.setFont(new java.awt.Font("Tahoma", 0, 12));
        aTxtTotalMatched.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aTxtTotalMatched.setMinimumSize(new java.awt.Dimension(60, 24));
        aTxtTotalMatched.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        aPnlBody.add(aTxtTotalMatched, gridBagConstraints);

        aLblTotalMatchedPageUnit.setFont(new java.awt.Font("Tahoma", 0, 12));
        aLblTotalMatchedPageUnit.setText("pages");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 11);
        aPnlBody.add(aLblTotalMatchedPageUnit, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 1);
        aPnlBody.add(separator2, gridBagConstraints);

        aLblHn.setFont(new java.awt.Font("Tahoma", 0, 12));
        aLblHn.setText("HN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlBody.add(aLblHn, gridBagConstraints);

        aTxtHn.setEditable(false);
        aTxtHn.setFont(new java.awt.Font("Tahoma", 0, 12));
        aTxtHn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aTxtHn.setMinimumSize(new java.awt.Dimension(120, 24));
        aTxtHn.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        aPnlBody.add(aTxtHn, gridBagConstraints);

        aTxtPatientName.setEditable(false);
        aTxtPatientName.setFont(new java.awt.Font("Tahoma", 0, 12));
        aTxtPatientName.setMinimumSize(new java.awt.Dimension(240, 24));
        aTxtPatientName.setPreferredSize(new java.awt.Dimension(240, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 11);
        aPnlBody.add(aTxtPatientName, gridBagConstraints);

        aLblProgress.setFont(new java.awt.Font("Tahoma", 0, 12));
        aLblProgress.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 11);
        aPnlBody.add(aLblProgress, gridBagConstraints);

        aStatusProgress.setFont(new java.awt.Font("Tahoma", 0, 12));
        aStatusProgress.setFocusable(false);
        aStatusProgress.setMinimumSize(new java.awt.Dimension(200, 24));
        aStatusProgress.setPreferredSize(new java.awt.Dimension(200, 24));
        aStatusProgress.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 12, 11, 11);
        aPnlBody.add(aStatusProgress, gridBagConstraints);

        getContentPane().add(aPnlBody, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-488)/2, (screenSize.height-267)/2, 488, 267);
    }// </editor-fold>//GEN-END:initComponents

    public void setConvertInProgress(boolean isInProgress)
    {
        this.aBtnStartScan.setEnabled(!isInProgress);
        this.aBtnCancel.setEnabled(isInProgress);
    }

    private void aBtnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aBtnCancelActionPerformed
    {//GEN-HEADEREND:event_aBtnCancelActionPerformed
        setConvertInProgress(false);
    }//GEN-LAST:event_aBtnCancelActionPerformed

    private void aBtnStartScanActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aBtnStartScanActionPerformed
    {//GEN-HEADEREND:event_aBtnStartScanActionPerformed
        setConvertInProgress(true);

         final ImageScan aImageScan = new ImageScan();
         aImageScan.setFolderName("OPD");
         aTimer = new Timer(1000, new ActionListener(){
            public void actionPerformed(ActionEvent evt)
            {
                aLblProgress.setText(aImageScan.getStatusText());
                aStatusProgress.setValue(aImageScan.getStatus());
                if(aImageScan.getStatus()==100)
                {
                    Toolkit.getDefaultToolkit().beep();
                    aTimer.stop();
                    setConvertInProgress(false);
                }
            }
         });
         aThread = new Thread(aImageScan);
         aThread.start();
         aTimer.start();

        setConvertInProgress(false);
    }//GEN-LAST:event_aBtnStartScanActionPerformed
    public final static String TEMP_FILENAME = "TempFilename";
    public final static String HEADER1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><jasperReport xmlns=\"http://jasperreports.sourceforge.net/jasperreports\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd\" name=\"";
    public final static String HEADER2 = "\" pageWidth=\"595\" pageHeight=\"842\" whenNoDataType=\"AllSectionsNoDetail\" columnWidth=\"595\" leftMargin=\"0\" rightMargin=\"0\" topMargin=\"0\" bottomMargin=\"0\" isSummaryNewPage=\"true\"><property name=\"ireport.zoom\" value=\"1.0\"/><property name=\"ireport.x\" value=\"0\"/><property name=\"ireport.y\" value=\"0\"/><parameter name=\"SUBREPORT_DIR\" class=\"java.lang.String\" isForPrompting=\"false\"><defaultValueExpression><![CDATA[\"";
    // public final static String PARAM_SUB_REPORT_DIR = "D:\\\\BPKHIS\\\\trunk\\\\Sources\\\\CodeJSP\\\\jboss\\\\server\\\\default\\\\deploy\\\\bpkjasper.war\\\\";
    public final static String REPORT_ELEMENT1 = "\"]]></defaultValueExpression></parameter><background><band height=\"842\" splitType=\"Stretch\"><image hAlign=\"Center\" vAlign=\"Middle\"><reportElement x=\"0\" y=\"0\" width=\"595\" height=\"842\"/><imageExpression class=\"java.lang.String\"><![CDATA[\"";
    // public final static String IMAGE_FULLPATH = "D:\\\\BPKHIS\\\\trunk\\\\Sources\\\\CodeJSP\\\\jboss\\\\server\\\\default\\\\deploy\\\\bpkimage.war\\\\imed_doc_new\\\\46\\\\0000003XX\\\\946000000391\\\\";
    public final static String REPORT_ELEMENT2 = "\"]]></imageExpression></image></band></background><title><band splitType=\"Stretch\"/></title><pageHeader><band splitType=\"Stretch\"/></pageHeader><columnHeader><band splitType=\"Stretch\"/></columnHeader><detail><band splitType=\"Stretch\"/></detail><columnFooter><band splitType=\"Stretch\"/></columnFooter><pageFooter><band splitType=\"Stretch\"/></pageFooter><summary>";
    public final static String HAS_NEXT_PAGE1 = "<band height=\"842\" splitType=\"Stretch\"><subreport><reportElement x=\"0\" y=\"0\" width=\"595\" height=\"842\"/><connectionExpression><![CDATA[$P{REPORT_CONNECTION}]]></connectionExpression><subreportExpression class=\"java.lang.String\"><![CDATA[$P{SUBREPORT_DIR} + \"";
    public final static String HAS_NEXT_PAGE2 = "\"]]></subreportExpression></subreport></band>";
    public final static String NO_NEXT_PAGE = "<band splitType=\"Stretch\"/>";
    public final static String FOOTER = "</summary></jasperReport>";

    /***
     * สำหรับสร้าง JRXML File 
     * @param reportName
     * @param inputImageAbsFilename
     * @param isHasNextPage
     * @param indexPage
     * @param outputJrxmlPath
     * @return     
    public static String generateJrxmlPage(String reportName, String inputImageAbsFilename, boolean isHasNextPage, int indexPage, String outputJrxmlPath)
    {
        String imgReportName = reportName;
        reportName = reportName.toUpperCase();
        reportName = reportName.replaceAll(".JPG", "");
        reportName = reportName.replaceAll(".JPEG", "");
        reportName = reportName.replaceAll(".GIF", "");
        reportName = reportName.replaceAll(".PNG", "");
        reportName = reportName.replaceAll(".BMP", "");

        StringBuilder jrxmlBuilder = new StringBuilder(HEADER1);
        jrxmlBuilder.append(reportName);
        jrxmlBuilder.append(HEADER2);
        jrxmlBuilder.append(MyString.addSlash(outputJrxmlPath));
        jrxmlBuilder.append(REPORT_ELEMENT1);
        jrxmlBuilder.append(MyString.addSlash(inputImageAbsFilename)).append(imgReportName);
        jrxmlBuilder.append(REPORT_ELEMENT2);
        if (isHasNextPage)
        {
            jrxmlBuilder.append(HAS_NEXT_PAGE1);
            jrxmlBuilder.append((reportName + "_" + (indexPage + 1) + ".jasper"));
            jrxmlBuilder.append(HAS_NEXT_PAGE2);
        }
        else
        {
            jrxmlBuilder.append(NO_NEXT_PAGE);
        }
        jrxmlBuilder.append(FOOTER);

        String filename = reportName + (isHasNextPage ? ("_" + indexPage) : "") + ".jrxml";
        String jrxmlAbsFilename = outputJrxmlPath + filename;
        writeFile(jrxmlAbsFilename, jrxmlBuilder.toString());

        return filename;
    }
     */

    /** Write text data to file 
    public static boolean writeFile(String filename, String data)
    {
        try
        {
            FileOutputStream fos = new FileOutputStream(filename);
            Writer out = new OutputStreamWriter(fos);
            out.write(data);
            out.close();
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            return false;
        }
        return true;
    }
    */

    /** 
    public static void deleteJrxmlFile(String jrxmlAbsFilename)
    {
        try
        {
            File file = new File(jrxmlAbsFilename);
            file.delete();
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    */

    /**
     * สำหรับ Convert JRXML File --> Jasper File --> PDF File
     * @param jrxmlFilename
     * @param inputJrxmlPath
     * @param outputPdfPath
     * @return     
    public static boolean convertPage(String jrxmlFilename, String inputJrxmlPath, String outputPdfPath)
    {
        boolean result = true;
        HashMap hm = new HashMap();
        Connection conn = null;
        String reportName = jrxmlFilename.replaceAll(".jrxml", "");
        String jasperFilename = reportName + ".jasper";

        try
        {
            System.out.println("Start convert ....");
            conn = DocScanDAOFactory.getConnection();

            JasperCompileManager.compileReportToFile(inputJrxmlPath + jrxmlFilename, inputJrxmlPath + jasperFilename);

            // Generate jasper print
            JasperPrint jprint = (JasperPrint) JasperFillManager.fillReport(inputJrxmlPath + jasperFilename, hm, conn);

            // Export pdf file
            JasperExportManager.exportReportToPdfFile(jprint, outputPdfPath + reportName + ".pdf");
            System.out.println("Done exporting reports to pdf");

            conn.close();
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }

        // สำหรับเคลียร์ file ออกหลัง convert
        File jasperFile = new File(inputJrxmlPath + jasperFilename);
        jasperFile.delete();
        
        return result;
    }
     */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        System.setProperty("bpk.debug", "true");

        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new FrmImageScan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aBtnCancel;
    private javax.swing.JButton aBtnStartScan;
    private javax.swing.JLabel aLblHn;
    private javax.swing.JLabel aLblProgress;
    private javax.swing.JLabel aLblTotalMatched;
    private javax.swing.JLabel aLblTotalMatchedPageUnit;
    private javax.swing.JLabel aLblTotalScan;
    private final javax.swing.JLabel aLblTotalScanPageUnit = new javax.swing.JLabel();
    private javax.swing.JPanel aPanelTop;
    private javax.swing.JPanel aPnlBody;
    private final javax.swing.JProgressBar aStatusProgress = new javax.swing.JProgressBar();
    private javax.swing.JTextField aTxtHn;
    private javax.swing.JTextField aTxtPatientName;
    private javax.swing.JTextField aTxtTotalMatched;
    private javax.swing.JTextField aTxtTotalScan;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    // End of variables declaration//GEN-END:variables

    public PatientVO getPatientVO()
    {
        return patientVO;
    }

    public void setPatientVO(PatientVO newPatientVO)
    {
        this.patientVO = newPatientVO;
    }
}
