/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmConvertDocScan.java
 *
 * Created on Jan 25, 2016, 6:18:22 PM
 */
package com.bpk.app.emrapp;

import com.bpk.core.emrcore.dao.DocScanDAOFactory;
import com.bpk.core.emrcore.dao.DocScanDAO;
import com.bpk.persistence.emrdto.BpkDocumentScanVO;
import com.bpk.persistence.emrdto.FolderVO;
import com.bpk.persistence.emrdto.PatientVO;
import com.bpk.persistence.emrdto.VisitVO;
import com.bpk.utility.EventNames;
import com.bpk.utility.MyString;
import com.bpk.utility.Utility;
import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.UIManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author SURACHAI.TO
 */
public class FrmImageScanByBarcode extends javax.swing.JFrame
{

    private PatientVO patientVO = null;
    Thread aThread = null;
    Timer aTimer = null;

    /** Creates new form FrmConvertDocScan */
    public FrmImageScanByBarcode()
    {
        try
        {
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new Theme());
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.Font aFont = new java.awt.Font("Tahoma", 0, 14);
            UIManager.put("OptionPane.font", aFont);
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }

        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        aPanelTop = new javax.swing.JPanel();
        aPnlStatusCard = new javax.swing.JPanel();
        aPnlStatusCardLogo = new javax.swing.JPanel();
        aLblLogo = new javax.swing.JLabel();
        aPnlStatusCardProgress = new javax.swing.JPanel();
        aLblProgress = new javax.swing.JLabel();
        aPnlTotalScan = new javax.swing.JPanel();
        aLblTotalScan = new javax.swing.JLabel();
        aTxtTotalScan = new javax.swing.JTextField();
        aLblTotalSuccess = new javax.swing.JLabel();
        aTxtTotalSuccess = new javax.swing.JTextField();
        aLblTotalFail = new javax.swing.JLabel();
        aTxtTotalFail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        aBtnScanByBarcode = new javax.swing.JButton();
        aBtnCancel = new javax.swing.JButton();
        aPnlBody = new javax.swing.JPanel();
        aPnlRight = new javax.swing.JPanel();
        aPnlPatientDetail = new javax.swing.JPanel();
        aLblHn = new javax.swing.JLabel();
        aTxtHn = new javax.swing.JTextField();
        aLblPatient = new javax.swing.JLabel();
        aTxtPatientName = new javax.swing.JTextField();
        aLblVn = new javax.swing.JLabel();
        aTxtVn = new javax.swing.JTextField();
        aLblDocDate = new javax.swing.JLabel();
        aTxtDocDate = new javax.swing.JTextField();
        aLblFolderName = new javax.swing.JLabel();
        aTxtFolderName = new javax.swing.JTextField();
        aLblDoctor = new javax.swing.JLabel();
        aTxtDoctor = new javax.swing.JTextField();
        ScrlBody = new javax.swing.JScrollPane();
        aPnlImagePreview = new javax.swing.JPanel();
        aLblImg = new javax.swing.JLabel();
        aMenuBar = new javax.swing.JMenuBar();
        aMenuFile = new javax.swing.JMenu();
        aMenuFileStart = new javax.swing.JMenuItem();
        aMenuFileCancel = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        aMenuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Scan by barcode");

        aPanelTop.setLayout(new java.awt.GridBagLayout());

        aPnlStatusCard.setLayout(new java.awt.CardLayout());

        aPnlStatusCardLogo.setBackground(new java.awt.Color(255, 255, 255));
        aPnlStatusCardLogo.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        aPnlStatusCardLogo.add(aLblLogo, gridBagConstraints);

        aPnlStatusCard.add(aPnlStatusCardLogo, "Logo");

        aPnlStatusCardProgress.setLayout(new java.awt.GridBagLayout());

        aLblProgress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblProgress.setText(" ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 11);
        aPnlStatusCardProgress.add(aLblProgress, gridBagConstraints);

        aStatusProgress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aStatusProgress.setFocusable(false);
        aStatusProgress.setMinimumSize(new java.awt.Dimension(200, 24));
        aStatusProgress.setPreferredSize(new java.awt.Dimension(200, 24));
        aStatusProgress.setStringPainted(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 12, 11, 11);
        aPnlStatusCardProgress.add(aStatusProgress, gridBagConstraints);

        aPnlStatusCard.add(aPnlStatusCardProgress, "Progress");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        aPanelTop.add(aPnlStatusCard, gridBagConstraints);

        aPnlTotalScan.setLayout(new java.awt.GridBagLayout());

        aLblTotalScan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblTotalScan.setText("Scanned:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlTotalScan.add(aLblTotalScan, gridBagConstraints);

        aTxtTotalScan.setEditable(false);
        aTxtTotalScan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtTotalScan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aTxtTotalScan.setMinimumSize(new java.awt.Dimension(60, 24));
        aTxtTotalScan.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 0);
        aPnlTotalScan.add(aTxtTotalScan, gridBagConstraints);

        aLblTotalSuccess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblTotalSuccess.setText("Success:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlTotalScan.add(aLblTotalSuccess, gridBagConstraints);

        aTxtTotalSuccess.setEditable(false);
        aTxtTotalSuccess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtTotalSuccess.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aTxtTotalSuccess.setMinimumSize(new java.awt.Dimension(60, 24));
        aTxtTotalSuccess.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 0);
        aPnlTotalScan.add(aTxtTotalSuccess, gridBagConstraints);

        aLblTotalFail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblTotalFail.setText("Fail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlTotalScan.add(aLblTotalFail, gridBagConstraints);

        aTxtTotalFail.setEditable(false);
        aTxtTotalFail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtTotalFail.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aTxtTotalFail.setMinimumSize(new java.awt.Dimension(60, 24));
        aTxtTotalFail.setPreferredSize(new java.awt.Dimension(60, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 0);
        aPnlTotalScan.add(aTxtTotalFail, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        aPnlTotalScan.add(jSeparator1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        aPnlTotalScan.add(jSeparator2, gridBagConstraints);

        aBtnScanByBarcode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aBtnScanByBarcode.setText("Start");
        aBtnScanByBarcode.setMargin(new java.awt.Insets(0, 0, 0, 0));
        aBtnScanByBarcode.setMaximumSize(new java.awt.Dimension(72, 32));
        aBtnScanByBarcode.setMinimumSize(new java.awt.Dimension(72, 32));
        aBtnScanByBarcode.setPreferredSize(new java.awt.Dimension(72, 32));
        aBtnScanByBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBtnScanByBarcodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 24, 0, 0);
        aPnlTotalScan.add(aBtnScanByBarcode, gridBagConstraints);

        aBtnCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        aBtnCancel.setEnabled(false);
        aBtnCancel.setLabel("Cancel");
        aBtnCancel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        aBtnCancel.setMaximumSize(new java.awt.Dimension(72, 32));
        aBtnCancel.setMinimumSize(new java.awt.Dimension(72, 32));
        aBtnCancel.setPreferredSize(new java.awt.Dimension(72, 32));
        aBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBtnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 11);
        aPnlTotalScan.add(aBtnCancel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        aPanelTop.add(aPnlTotalScan, gridBagConstraints);

        getContentPane().add(aPanelTop, java.awt.BorderLayout.PAGE_START);

        aPnlBody.setLayout(new java.awt.BorderLayout());

        aPnlRight.setLayout(new java.awt.GridBagLayout());

        aPnlPatientDetail.setLayout(new java.awt.GridBagLayout());

        aLblHn.setFont(new java.awt.Font("Tahoma", 0, 12));
        aLblHn.setText("HN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlPatientDetail.add(aLblHn, gridBagConstraints);

        aTxtHn.setEditable(false);
        aTxtHn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtHn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aTxtHn.setMinimumSize(new java.awt.Dimension(120, 24));
        aTxtHn.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        aPnlPatientDetail.add(aTxtHn, gridBagConstraints);

        aLblPatient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblPatient.setText("Patient:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlPatientDetail.add(aLblPatient, gridBagConstraints);

        aTxtPatientName.setEditable(false);
        aTxtPatientName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtPatientName.setMinimumSize(new java.awt.Dimension(240, 24));
        aTxtPatientName.setPreferredSize(new java.awt.Dimension(240, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 11);
        aPnlPatientDetail.add(aTxtPatientName, gridBagConstraints);

        aLblVn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblVn.setText("VN:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
        aPnlPatientDetail.add(aLblVn, gridBagConstraints);

        aTxtVn.setEditable(false);
        aTxtVn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtVn.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        aTxtVn.setMinimumSize(new java.awt.Dimension(120, 24));
        aTxtVn.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 0, 0);
        aPnlPatientDetail.add(aTxtVn, gridBagConstraints);

        aLblDocDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblDocDate.setText("Print Date:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 0, 0);
        aPnlPatientDetail.add(aLblDocDate, gridBagConstraints);

        aTxtDocDate.setEditable(false);
        aTxtDocDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtDocDate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        aTxtDocDate.setMinimumSize(new java.awt.Dimension(240, 24));
        aTxtDocDate.setPreferredSize(new java.awt.Dimension(240, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 0, 11);
        aPnlPatientDetail.add(aTxtDocDate, gridBagConstraints);

        aLblFolderName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblFolderName.setText("Folder:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 11, 0);
        aPnlPatientDetail.add(aLblFolderName, gridBagConstraints);

        aTxtFolderName.setEditable(false);
        aTxtFolderName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtFolderName.setMinimumSize(new java.awt.Dimension(120, 24));
        aTxtFolderName.setPreferredSize(new java.awt.Dimension(120, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 11, 0);
        aPnlPatientDetail.add(aTxtFolderName, gridBagConstraints);

        aLblDoctor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aLblDoctor.setText("Doctor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 12, 11, 0);
        aPnlPatientDetail.add(aLblDoctor, gridBagConstraints);

        aTxtDoctor.setEditable(false);
        aTxtDoctor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtDoctor.setMinimumSize(new java.awt.Dimension(240, 24));
        aTxtDoctor.setPreferredSize(new java.awt.Dimension(240, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 11, 11);
        aPnlPatientDetail.add(aTxtDoctor, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 4);
        aPnlRight.add(aPnlPatientDetail, gridBagConstraints);

        aPnlImagePreview.setLayout(new java.awt.BorderLayout());
        aPnlImagePreview.add(aLblImg, java.awt.BorderLayout.CENTER);

        ScrlBody.setViewportView(aPnlImagePreview);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 4, 5);
        aPnlRight.add(ScrlBody, gridBagConstraints);

        aPnlBody.add(aPnlRight, java.awt.BorderLayout.CENTER);

        getContentPane().add(aPnlBody, java.awt.BorderLayout.CENTER);

        aMenuFile.setText("File");

        aMenuFileStart.setText("Start scan");
        aMenuFileStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMenuFileStartActionPerformed(evt);
            }
        });
        aMenuFile.add(aMenuFileStart);

        aMenuFileCancel.setText("Cancel scan");
        aMenuFileCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMenuFileCancelActionPerformed(evt);
            }
        });
        aMenuFile.add(aMenuFileCancel);
        aMenuFile.add(jSeparator3);

        aMenuExit.setText("Exit");
        aMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMenuExitActionPerformed(evt);
            }
        });
        aMenuFile.add(aMenuExit);

        aMenuBar.add(aMenuFile);

        setJMenuBar(aMenuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-536)/2, (screenSize.height-712)/2, 536, 712);
    }// </editor-fold>//GEN-END:initComponents

    public void setConvertInProgress(boolean isInProgress)
    {
        this.aBtnScanByBarcode.setEnabled(!isInProgress);
        this.aBtnCancel.setEnabled(isInProgress);

        if (isInProgress)
        {
            showStatusCard("Progress");
        }
        else
        {
            showStatusCard("Card");
        }
    }

    private void aBtnScanByBarcodeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aBtnScanByBarcodeActionPerformed
    {//GEN-HEADEREND:event_aBtnScanByBarcodeActionPerformed
        setConvertInProgress(true);

        final ImageScan aImageScan = new ImageScan();
        aImageScan.setFolderName("DOS");
        aTimer = new Timer(1000, new ActionListener()
        {

            public void actionPerformed(ActionEvent evt)
            {
                aTxtTotalScan.setText(String.valueOf(aImageScan.getNumScan()));
                aTxtTotalSuccess.setText(String.valueOf(aImageScan.getNumSuccess()));
                aTxtTotalFail.setText(String.valueOf(aImageScan.getNumFail()));
                aLblProgress.setText(aImageScan.getStatusText());
                aStatusProgress.setValue(aImageScan.getStatus());

                BpkDocumentScanVO tmpBpkDocumentScanVO = aImageScan.getLastBpkDocumentScanVO();
                if (tmpBpkDocumentScanVO != null)
                {
                    aTxtHn.setText(tmpBpkDocumentScanVO.getHn());
                    aTxtPatientName.setText(tmpBpkDocumentScanVO.getPatientName());
                }
                if (aImageScan.getStatus() == 100)
                {
                    Toolkit.getDefaultToolkit().beep();
                    aTimer.stop();
                    setConvertInProgress(false);
                }

                try
                {
                    // aLblImg.setIcon(new ImageIcon(ImageIO.read(new File(aImageScan.getLastImage()))));
                    aLblImg.setIcon(rescaleImage(new File(aImageScan.getLastImage()), aPnlImagePreview.getHeight(), aPnlImagePreview.getWidth()));
                }
                catch (Exception ex)
                {
                    // Logger.getLogger(FrmImageScanByBarcode.class.getName()).log(Level.SEVERE, null, ex);
                }

                if ("Finished".equals(aLblProgress.getText()))
                {
                    setConvertInProgress(false);
                    return;
                }
            }
        });
        aThread = new Thread(aImageScan);
        aThread.start();
        aTimer.start();

        setConvertInProgress(false);
    }//GEN-LAST:event_aBtnScanByBarcodeActionPerformed

    public ImageIcon rescaleImage(File source, int maxHeight, int maxWidth)
    {
        // เพื่อให้ thread อื่นๆ สามารถ move file ได้
        source.setWritable(true);

        int newHeight = 0, newWidth = 0;        // Variables for the new height and width
        int priorHeight = 0, priorWidth = 0;
        BufferedImage image = null;
        ImageIcon sizeImage;

        try
        {
            image = ImageIO.read(source);        // get the image
        }
        catch (Exception e)
        {

            e.printStackTrace();
            System.out.println("Picture upload attempted & failed");
        }

        sizeImage = new ImageIcon(image);

        if (sizeImage != null)
        {
            priorHeight = sizeImage.getIconHeight();
            priorWidth = sizeImage.getIconWidth();
        }

        // Calculate the correct new height and width
        if ((float) priorHeight / (float) priorWidth > (float) maxHeight / (float) maxWidth)
        {
            newWidth = maxWidth;
            newHeight = (int) (((float) priorHeight / (float) priorWidth) * (float) newWidth);
        }
        else
        {
            newHeight = maxHeight;
            newWidth = (int) (((float) priorWidth / (float) priorHeight) * (float) newHeight);
        }


        // Resize the image

        // 1. Create a new Buffered Image and Graphic2D object
        BufferedImage resizedImg = new BufferedImage(newWidth, newHeight, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedImg.createGraphics();

        // 2. Use the Graphic object to draw a new image to the image in the buffer
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(image, 0, 0, newWidth, newHeight, null);
        g2.dispose();

        // 3. Convert the buffered image into an ImageIcon for return
        return (new ImageIcon(resizedImg));
    }

    public void showStatusCard(String cardName)
    {
        CardLayout card = (CardLayout) this.aPnlStatusCard.getLayout();
        card.show(this.aPnlStatusCard, cardName);
    }

    private void aBtnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aBtnCancelActionPerformed
    {//GEN-HEADEREND:event_aBtnCancelActionPerformed
        // setConvertInProgress(false);
}//GEN-LAST:event_aBtnCancelActionPerformed

    private void aMenuFileStartActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aMenuFileStartActionPerformed
    {//GEN-HEADEREND:event_aMenuFileStartActionPerformed
        aBtnScanByBarcodeActionPerformed(evt);
    }//GEN-LAST:event_aMenuFileStartActionPerformed

    private void aMenuFileCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aMenuFileCancelActionPerformed
    {//GEN-HEADEREND:event_aMenuFileCancelActionPerformed
        aBtnCancelActionPerformed(evt);
    }//GEN-LAST:event_aMenuFileCancelActionPerformed

    private void aMenuExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aMenuExitActionPerformed
    {//GEN-HEADEREND:event_aMenuExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_aMenuExitActionPerformed
    public final static String TEMP_FILENAME = "TempFilename";
    public final static String HEADER1 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?><jasperReport xmlns=\"http://jasperreports.sourceforge.net/jasperreports\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd\" name=\"";
    public final static String HEADER2 = "\" pageWidth=\"595\" pageHeight=\"842\" whenNoDataType=\"AllSectionsNoDetail\" columnWidth=\"595\" leftMargin=\"0\" rightMargin=\"0\" topMargin=\"0\" bottomMargin=\"0\" isSummaryNewPage=\"true\"><property name=\"ireport.zoom\" value=\"1.0\"/><property name=\"ireport.x\" value=\"0\"/><property name=\"ireport.y\" value=\"0\"/><parameter name=\"SUBREPORT_DIR\" class=\"java.lang.String\" isForPrompting=\"false\"><defaultValueExpression><![CDATA[\"";
    // public final static String PARAM_SUB_REPORT_DIR = "D:\\\\BPKHIS\\\\trunk\\\\Sources\\\\CodeJSP\\\\jboss\\\\server\\\\default\\\\deploy\\\\bpkjasper.war\\\\";
    public final static String REPORT_ELEMENT1 = "\"]]></defaultValueExpression></parameter><background><band height=\"842\" splitType=\"Stretch\"><image hAlign=\"Center\" vAlign=\"Middle\"><reportElement x=\"0\" y=\"0\" width=\"595\" height=\"842\"/><imageExpression class=\"java.lang.String\"><![CDATA[\"";
    // public final static String IMAGE_FULLPATH = "D:\\\\BPKHIS\\\\trunk\\\\Sources\\\\CodeJSP\\\\jboss\\\\server\\\\default\\\\deploy\\\\bpkimage.war\\\\imed_doc_new\\\\46\\\\0000003XX\\\\946000000391\\\\";
    public final static String REPORT_ELEMENT2 = "\"]]></imageExpression></image></band></background><title><band splitType=\"Stretch\"/></title><pageHeader><band splitType=\"Stretch\"/></pageHeader><columnHeader><band splitType=\"Stretch\"/></columnHeader><detail><band splitType=\"Stretch\"/></detail><columnFooter><band splitType=\"Stretch\"/></columnFooter><pageFooter><band splitType=\"Stretch\"/></pageFooter><summary>";
    public final static String HAS_NEXT_PAGE1 = "<band height=\"842\" splitType=\"Stretch\"><subreport><reportElement x=\"0\" y=\"0\" width=\"595\" height=\"842\"/><connectionExpression><![CDATA[$P{REPORT_CONNECTION}]]></connectionExpression><subreportExpression class=\"java.lang.String\"><![CDATA[$P{SUBREPORT_DIR} + \"";
    public final static String HAS_NEXT_PAGE2 = "\"]]></subreportExpression></subreport></band>";
    public final static String NO_NEXT_PAGE = "<band splitType=\"Stretch\"/>";
    public final static String FOOTER = "</summary></jasperReport>";

    /***
     * สำหรับสร้าง JRXML File 
     * @param reportName
     * @param inputImageAbsFilename
     * @param isHasNextPage
     * @param indexPage
     * @param outputJrxmlPath
     * @return     
    public static String generateJrxmlPage(String reportName, String inputImageAbsFilename, boolean isHasNextPage, int indexPage, String outputJrxmlPath)
    {
    String imgReportName = reportName;
    reportName = reportName.toUpperCase();
    reportName = reportName.replaceAll(".JPG", "");
    reportName = reportName.replaceAll(".JPEG", "");
    reportName = reportName.replaceAll(".GIF", "");
    reportName = reportName.replaceAll(".PNG", "");
    reportName = reportName.replaceAll(".BMP", "");

    StringBuilder jrxmlBuilder = new StringBuilder(HEADER1);
    jrxmlBuilder.append(reportName);
    jrxmlBuilder.append(HEADER2);
    jrxmlBuilder.append(MyString.addSlash(outputJrxmlPath));
    jrxmlBuilder.append(REPORT_ELEMENT1);
    jrxmlBuilder.append(MyString.addSlash(inputImageAbsFilename)).append(imgReportName);
    jrxmlBuilder.append(REPORT_ELEMENT2);
    if (isHasNextPage)
    {
    jrxmlBuilder.append(HAS_NEXT_PAGE1);
    jrxmlBuilder.append((reportName + "_" + (indexPage + 1) + ".jasper"));
    jrxmlBuilder.append(HAS_NEXT_PAGE2);
    }
    else
    {
    jrxmlBuilder.append(NO_NEXT_PAGE);
    }
    jrxmlBuilder.append(FOOTER);

    String filename = reportName + (isHasNextPage ? ("_" + indexPage) : "") + ".jrxml";
    String jrxmlAbsFilename = outputJrxmlPath + filename;
    writeFile(jrxmlAbsFilename, jrxmlBuilder.toString());

    return filename;
    }
     */
    /** Write text data to file 
    public static boolean writeFile(String filename, String data)
    {
    try
    {
    FileOutputStream fos = new FileOutputStream(filename);
    Writer out = new OutputStreamWriter(fos);
    out.write(data);
    out.close();
    }
    catch (Exception ex)
    {
    ex.printStackTrace();
    return false;
    }
    return true;
    }
     */
    /** 
    public static void deleteJrxmlFile(String jrxmlAbsFilename)
    {
    try
    {
    File file = new File(jrxmlAbsFilename);
    file.delete();
    }
    catch(Exception ex)
    {
    ex.printStackTrace();
    }
    }
     */
    /**
     * สำหรับ Convert JRXML File --> Jasper File --> PDF File
     * @param jrxmlFilename
     * @param inputJrxmlPath
     * @param outputPdfPath
     * @return     
    public static boolean convertPage(String jrxmlFilename, String inputJrxmlPath, String outputPdfPath)
    {
    boolean result = true;
    HashMap hm = new HashMap();
    Connection conn = null;
    String reportName = jrxmlFilename.replaceAll(".jrxml", "");
    String jasperFilename = reportName + ".jasper";

    try
    {
    System.out.println("Start convert ....");
    conn = DocScanDAOFactory.getConnection();

    JasperCompileManager.compileReportToFile(inputJrxmlPath + jrxmlFilename, inputJrxmlPath + jasperFilename);

    // Generate jasper print
    JasperPrint jprint = (JasperPrint) JasperFillManager.fillReport(inputJrxmlPath + jasperFilename, hm, conn);

    // Export pdf file
    JasperExportManager.exportReportToPdfFile(jprint, outputPdfPath + reportName + ".pdf");
    System.out.println("Done exporting reports to pdf");

    conn.close();
    }
    catch (Exception e)
    {
    e.printStackTrace();
    }

    // สำหรับเคลียร์ file ออกหลัง convert
    File jasperFile = new File(inputJrxmlPath + jasperFilename);
    jasperFile.delete();

    return result;
    }
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {

        System.setProperty("bpk.debug", "true");

        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new FrmImageScanByBarcode().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrlBody;
    private javax.swing.JButton aBtnCancel;
    private javax.swing.JButton aBtnScanByBarcode;
    private javax.swing.JLabel aLblDocDate;
    private javax.swing.JLabel aLblDoctor;
    private javax.swing.JLabel aLblFolderName;
    private javax.swing.JLabel aLblHn;
    private javax.swing.JLabel aLblImg;
    private javax.swing.JLabel aLblLogo;
    private javax.swing.JLabel aLblPatient;
    private javax.swing.JLabel aLblProgress;
    private javax.swing.JLabel aLblTotalFail;
    private javax.swing.JLabel aLblTotalScan;
    private javax.swing.JLabel aLblTotalSuccess;
    private javax.swing.JLabel aLblVn;
    private javax.swing.JMenuBar aMenuBar;
    private javax.swing.JMenuItem aMenuExit;
    private javax.swing.JMenu aMenuFile;
    private javax.swing.JMenuItem aMenuFileCancel;
    private javax.swing.JMenuItem aMenuFileStart;
    private javax.swing.JPanel aPanelTop;
    private javax.swing.JPanel aPnlBody;
    private javax.swing.JPanel aPnlImagePreview;
    private javax.swing.JPanel aPnlPatientDetail;
    private javax.swing.JPanel aPnlRight;
    private javax.swing.JPanel aPnlStatusCard;
    private javax.swing.JPanel aPnlStatusCardLogo;
    private javax.swing.JPanel aPnlStatusCardProgress;
    private javax.swing.JPanel aPnlTotalScan;
    private final javax.swing.JProgressBar aStatusProgress = new javax.swing.JProgressBar();
    private javax.swing.JTextField aTxtDocDate;
    private javax.swing.JTextField aTxtDoctor;
    private javax.swing.JTextField aTxtFolderName;
    private javax.swing.JTextField aTxtHn;
    private javax.swing.JTextField aTxtPatientName;
    private javax.swing.JTextField aTxtTotalFail;
    private javax.swing.JTextField aTxtTotalScan;
    private javax.swing.JTextField aTxtTotalSuccess;
    private javax.swing.JTextField aTxtVn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

    public PatientVO getPatientVO()
    {
        return patientVO;
    }

    public void setPatientVO(PatientVO newPatientVO)
    {
        this.patientVO = newPatientVO;
    }
}
