package com.bpk.app.emrapp;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author SURACHAI.TO
 */
public class FrmLogin extends javax.swing.JFrame
{
    private FrmImageScan parent = null;
    Timer aTimer = null;

    /** Creates new form FrmLogin */
    public FrmLogin()
    {
        try
        {
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new Theme());
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.Font aFont = new java.awt.Font("Tahoma", 0, 14);
            UIManager.put("OptionPane.font", aFont);
        } catch (Exception ex)
        {
            ex.printStackTrace();
        }

        initComponents();

        aTimer = new Timer(1000, new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                    setProgressStatus(parent.getStatus());

                    if (parent.getStatus() == 100)
                    {
                        Toolkit.getDefaultToolkit().beep();
                        aTimer.stop();
                    }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aPrgStatus = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login to Document Scan");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        aPrgStatus.setMinimumSize(new java.awt.Dimension(300, 28));
        aPrgStatus.setPreferredSize(new java.awt.Dimension(300, 28));
        getContentPane().add(aPrgStatus, new java.awt.GridBagConstraints());

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-320)/2, (screenSize.height-72)/2, 320, 72);
    }// </editor-fold>//GEN-END:initComponents

    protected void setProgressStatus(int value)
    {
        this.aPrgStatus.setValue(value);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new FrmLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar aPrgStatus;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the parent
     */
    public FrmImageScan getParent()
    {
        return parent;
    }

    /**
     * @param parent the parent to set
     */
    public void setParent(FrmImageScan parent)
    {
        this.parent = parent;
    }
}
