/*
 * FrmSqlServerToPg.java
 *
 * Created on Aug 16, 2015, 8:55:43 AM
 */
package com.bpk.pgToSqlServer.ui;

import com.bpk.pgToSqlServer.dao.SqlServerToPgDAO;
import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UIManager;

/**
 *
 * @author surachai.tw
 */
public class FrmSqlServerToPg extends javax.swing.JFrame
{

    /** Creates new form FrmSqlServerToPg */
    public FrmSqlServerToPg()
    {
        try
        {
            javax.swing.plaf.metal.MetalLookAndFeel.setCurrentTheme(new Theme());
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            java.awt.Font aFont = new java.awt.Font("Tahoma", 0, 14);
            UIManager.put("OptionPane.font", aFont);
        } catch (Exception ex)
        {
            ex.printStackTrace();
        }

        initComponents();

        ListSqlFileCellRenderer listCellRender = new ListSqlFileCellRenderer();
        this.aLstSqlFile.setCellRenderer(listCellRender);

        SqlServerToPgDAO tmpXlsReportDAO = new SqlServerToPgDAO();
        this.aTxtSqlPath.setText(tmpXlsReportDAO.getDefaultPathSql());
        tmpXlsReportDAO = null;

        this.loadSqlFileFromPath();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        aPnlTop = new javax.swing.JPanel();
        aLblSqlPath = new javax.swing.JLabel();
        aTxtSqlPath = new javax.swing.JTextField();
        aBtnExeSqlCommand = new javax.swing.JButton();
        aLblFromDate = new javax.swing.JLabel();
        aTxtFromDate = new javax.swing.JTextField();
        aLblTo = new javax.swing.JLabel();
        aTxtToDate = new javax.swing.JTextField();
        aLblOption = new javax.swing.JLabel();
        aCmbOption = new javax.swing.JComboBox();
        aPnlBody = new javax.swing.JPanel();
        aScrlPaneSqlFile = new javax.swing.JScrollPane();
        aLstSqlFile = new javax.swing.JList();
        aMenuBar = new javax.swing.JMenuBar();
        aMenu = new javax.swing.JMenu();
        aMenuItemReloadFile = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        aMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("language"); // NOI18N
        setTitle(bundle.getString("FrmExport.title")); // NOI18N
        setMinimumSize(new java.awt.Dimension(720, 152));
        setResizable(false);

        aPnlTop.setLayout(new java.awt.GridBagLayout());

        aLblSqlPath.setText(bundle.getString("FrmExport.aLblSqlPath")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlTop.add(aLblSqlPath, gridBagConstraints);

        aTxtSqlPath.setFont(new java.awt.Font("Tahoma", 0, 12));
        aTxtSqlPath.setText("D:\\BPK\\trunk\\SqlServerToPg\\sql");
        aTxtSqlPath.setMinimumSize(new java.awt.Dimension(200, 24));
        aTxtSqlPath.setPreferredSize(new java.awt.Dimension(200, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 11);
        aPnlTop.add(aTxtSqlPath, gridBagConstraints);

        aBtnExeSqlCommand.setFont(new java.awt.Font("Tahoma", 1, 12));
        aBtnExeSqlCommand.setText(bundle.getString("FrmExport.aBtnExeSqlCommand")); // NOI18N
        aBtnExeSqlCommand.setMargin(new java.awt.Insets(2, 2, 2, 2));
        aBtnExeSqlCommand.setMaximumSize(new java.awt.Dimension(72, 28));
        aBtnExeSqlCommand.setMinimumSize(new java.awt.Dimension(72, 28));
        aBtnExeSqlCommand.setPreferredSize(new java.awt.Dimension(72, 28));
        aBtnExeSqlCommand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBtnExeSqlCommandActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 11);
        aPnlTop.add(aBtnExeSqlCommand, gridBagConstraints);

        aLblFromDate.setText(bundle.getString("FrmExport.aLblDate")); // NOI18N
        aLblFromDate.setToolTipText("YYYY-MM-DD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 5, 0, 0);
        aPnlTop.add(aLblFromDate, gridBagConstraints);

        aTxtFromDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtFromDate.setText("2016-03-01");
        aTxtFromDate.setToolTipText("Input format YYYY-MM-DD");
        aTxtFromDate.setMinimumSize(new java.awt.Dimension(80, 24));
        aTxtFromDate.setPreferredSize(new java.awt.Dimension(80, 24));
        aTxtFromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTxtFromDateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        aPnlTop.add(aTxtFromDate, gridBagConstraints);

        aLblTo.setText(" - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        aPnlTop.add(aLblTo, gridBagConstraints);

        aTxtToDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aTxtToDate.setText("2016-03-01");
        aTxtToDate.setToolTipText("Input format YYYY-MM-DD");
        aTxtToDate.setMinimumSize(new java.awt.Dimension(80, 24));
        aTxtToDate.setPreferredSize(new java.awt.Dimension(80, 24));
        aTxtToDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTxtToDateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        aPnlTop.add(aTxtToDate, gridBagConstraints);

        aLblOption.setText("Option:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        aPnlTop.add(aLblOption, gridBagConstraints);

        aCmbOption.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SPLIT (1 folder = 1 day)", "COLLECT (1 folder = all day in range)" }));
        aCmbOption.setMinimumSize(new java.awt.Dimension(210, 24));
        aCmbOption.setPreferredSize(new java.awt.Dimension(210, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 2, 0, 0);
        aPnlTop.add(aCmbOption, gridBagConstraints);

        getContentPane().add(aPnlTop, java.awt.BorderLayout.NORTH);

        aPnlBody.setLayout(new java.awt.GridBagLayout());

        aScrlPaneSqlFile.setFont(new java.awt.Font("Tahoma", 0, 12));

        aLstSqlFile.setFont(new java.awt.Font("Tahoma", 0, 12));
        aScrlPaneSqlFile.setViewportView(aLstSqlFile);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 11, 11);
        aPnlBody.add(aScrlPaneSqlFile, gridBagConstraints);

        getContentPane().add(aPnlBody, java.awt.BorderLayout.CENTER);

        aMenu.setMnemonic('F');
        aMenu.setText("File");

        aMenuItemReloadFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        aMenuItemReloadFile.setFont(new java.awt.Font("Tahoma", 0, 14));
        aMenuItemReloadFile.setMnemonic('R');
        aMenuItemReloadFile.setText(bundle.getString("FrmExport.aMenuItemReloadFile")); // NOI18N
        aMenuItemReloadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMenuItemReloadFileActionPerformed(evt);
            }
        });
        aMenu.add(aMenuItemReloadFile);
        aMenu.add(jSeparator1);

        aMenuItemExit.setFont(new java.awt.Font("Tahoma", 0, 14));
        aMenuItemExit.setMnemonic('x');
        aMenuItemExit.setText(bundle.getString("FrmExport.aMenuItemExit")); // NOI18N
        aMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aMenuItemExitActionPerformed(evt);
            }
        });
        aMenu.add(aMenuItemExit);

        aMenuBar.add(aMenu);

        setJMenuBar(aMenuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-720)/2, (screenSize.height-480)/2, 720, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void aTxtFromDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aTxtFromDateActionPerformed
    {//GEN-HEADEREND:event_aTxtFromDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTxtFromDateActionPerformed

    private void loadSqlFileFromPath()
    {
        try
        {
            File pathSql = new File(this.aTxtSqlPath.getText().trim());
            if (pathSql.exists())
            {
                File[] files = pathSql.listFiles(new FileFilterSql("SQL File", "sql"));
                List listFiles = new ArrayList(files.length);

                for (int i = 0; i < files.length; i++)
                {
                    // System.out.println(files[i].getName());
                    if(files[i].isFile())
                        listFiles.add(files[i].getName());
                }

                this.aLstSqlFile.setListData(listFiles.toArray());
            }
        } catch (Exception ex)
        {
            ex.printStackTrace();
        } finally
        {
        }
    }

    /**
     *
     * @param backDate หมายถึงให้ย้อนไปกี่วัน
     * @return YYYY-MM-DD
     */
    public static String getCurrentDateForExecute(int backDate)
    {
        NumberFormat nf2 = NumberFormat.getInstance();
        nf2.setGroupingUsed(false);
        nf2.setMaximumIntegerDigits(2);
        nf2.setMinimumIntegerDigits(2);
        nf2.setMaximumFractionDigits(0);
        nf2.setMinimumFractionDigits(0);
        NumberFormat nf4 = NumberFormat.getInstance();
        nf4.setGroupingUsed(false);
        nf4.setMaximumIntegerDigits(4);
        nf4.setMinimumIntegerDigits(4);
        nf4.setMaximumFractionDigits(0);
        nf4.setMinimumFractionDigits(0);
        Calendar aCal = Calendar.getInstance(new Locale("en", "UK"));
        try
        {
            if(backDate!=0)
            {
                aCal.set(Calendar.DAY_OF_MONTH, aCal.get(Calendar.DAY_OF_MONTH)+backDate);
            }

            String YY = nf4.format(aCal.get(Calendar.YEAR));
            String MM = nf2.format(aCal.get(Calendar.MONTH)+1);
            String DD = nf2.format(aCal.get(Calendar.DAY_OF_MONTH));

            return YY+"-"+MM+"-"+DD;
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        finally
        {
            nf2 = null;
            nf4 = null;
            aCal = null;
        }
        return "";
    }

    private String getCurrentDateTimeForFolder()
    {
        NumberFormat nf2 = NumberFormat.getInstance();
        nf2.setGroupingUsed(false);
        nf2.setMaximumIntegerDigits(2);
        nf2.setMinimumIntegerDigits(2);
        nf2.setMaximumFractionDigits(0);
        nf2.setMinimumFractionDigits(0);
        Calendar aCal = Calendar.getInstance(new Locale("en", "UK"));
        try
        {
            String YY = nf2.format(aCal.get(Calendar.YEAR));
            String MM = nf2.format(aCal.get(Calendar.MONTH)+1);
            String DD = nf2.format(aCal.get(Calendar.DAY_OF_MONTH));
            String HH = nf2.format(aCal.get(Calendar.HOUR_OF_DAY));
            String mm = nf2.format(aCal.get(Calendar.MINUTE));
            String ss = nf2.format(aCal.get(Calendar.SECOND));

            return YY+MM+DD+HH+mm+ss;
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        finally
        {
            nf2 = null;
            aCal = null;
        }
        return "";
    }

    public void execute()
    {
        this.execute(this.aTxtFromDate.getText().trim(), this.aTxtToDate.getText().trim());
    }

    public void execute(String inputFromDate, String inputToDate)
    {
        this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        this.loadSqlFileFromPath();
        this.aTxtSqlPath.setEditable(false);
        this.aTxtFromDate.setEditable(false);
        this.aTxtToDate.setEditable(false);

        // ตรวจสอบ SQL Path ต้องกำหนดรูปแบบให้ถูกต้อง
        String pathSql = this.aTxtSqlPath.getText().trim();
        if (!pathSql.endsWith("\\"))
        {
            pathSql = pathSql + "\\";
        }
        this.aTxtSqlPath.setText(pathSql);
        File chkPathSql = new File(pathSql);
        if (!chkPathSql.exists())
        {
            this.setCursor(Cursor.getDefaultCursor());
            this.aTxtSqlPath.setEditable(true);
            this.aTxtFromDate.setEditable(true);
            this.aTxtToDate.setEditable(true);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("language").getString("FrmExport.aLblSqlPath") + " " + pathSql + " doesn't exist", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SqlServerToPgDAO aPgToSqlServerDAO = new SqlServerToPgDAO();
        BufferedReader in = null;
        try
        {
            ListModel listMdl = this.aLstSqlFile.getModel();
            for (int i = 0; i < listMdl.getSize(); i++)
            {
                String fileName = (String) listMdl.getElementAt(i);

                String line = null;
                StringBuilder sql = new StringBuilder();
                in = new BufferedReader(new FileReader(new File(this.aTxtSqlPath.getText().trim() + fileName)));
                for (int j = 0; (line = in.readLine()) != null; j++)
                {
                    sql.append(line).append(" ");
                }
                in.close();

                // Replace parameter ด้วย aTxtFromDate, aTxtToDate 
                String sqlCmdText = sql.toString();
                StringBuilder sqlCmdExe = new StringBuilder();
                for (int idxOfParam = sqlCmdText.indexOf("$P"), startIdx = 0; idxOfParam != -1;)
                {
                    sqlCmdExe.append(sqlCmdText.substring(startIdx, idxOfParam));
                    String tmpSqlCmdText = sqlCmdText.substring(idxOfParam);
                    String tmpParam = tmpSqlCmdText.substring(0, tmpSqlCmdText.indexOf('}'));

                    if(this.aCmbOption.getModel().getSelectedItem().toString().toUpperCase().indexOf("SPLIT")!=-1)
                    {
                        // กรณีที่ทำแบบ Split ส่วนของ dBeginDate, dEndDate ใช้วันที่เดียวกัน
                        sqlCmdExe.append(inputFromDate);
                    }
                    else
                    {
                        // กรณีที่ Collect ต้องตรวจสอบ dBeginDate และ dEndDate ตรงกับ input
                        if(tmpParam.toUpperCase().indexOf("END")!=-1)
                        {
                            sqlCmdExe.append(inputToDate);
                        }
                        else
                        {
                            // if(tmpParam.toUpperCase().indexOf("Begin")!=-1)
                            sqlCmdExe.append(inputFromDate);
                        }
                    }

                    sqlCmdText = tmpSqlCmdText;
                    sqlCmdText = sqlCmdText.substring(sqlCmdText.indexOf("}") + 1);
                    idxOfParam = sqlCmdText.indexOf("$P");
                }
                sqlCmdExe.append(sqlCmdText);
                System.out.println(sqlCmdExe.toString());

                aPgToSqlServerDAO.exportData(fileName.replaceAll(".sql", ""), sqlCmdExe.toString());
            }
        }
        catch(FileNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        } finally
        {
            this.setCursor(Cursor.getDefaultCursor());
            this.aTxtSqlPath.setEditable(true);
            this.aTxtFromDate.setEditable(true);
            this.aTxtToDate.setEditable(true);
        }
    }

    public static Date getDateChristFromString(String yyyy_mm_dd)
    {
        if (yyyy_mm_dd != null && (yyyy_mm_dd.length() == 10))
        {
            String yyyy = yyyy_mm_dd.substring(0, 4);
            String mm = yyyy_mm_dd.substring(5, 7);
            String dd = yyyy_mm_dd.substring(8, 10);

            Calendar cal = Calendar.getInstance(Locale.UK);
            int y = Integer.parseInt(yyyy);
            if (y > 2500)
            {
                y = y - 543;
            }
            cal.set(Calendar.YEAR, y);
            cal.set(Calendar.MONTH, Integer.parseInt(mm) - 1);
            cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(dd));

            return cal.getTime();
        }

        return null;
    }

    public static String convertDate2StdFormat(java.util.Date aDate)
    {
        if (aDate != null)
        {
            Calendar aCal = Calendar.getInstance(Locale.ENGLISH);
            StringBuilder stdDate = new StringBuilder();
            NumberFormat nf2 = NumberFormat.getInstance();
            NumberFormat nf4 = NumberFormat.getInstance();

            nf2.setMaximumFractionDigits(0);
            nf2.setMinimumFractionDigits(0);
            nf2.setMaximumIntegerDigits(2);
            nf2.setMinimumIntegerDigits(2);
            nf2.setGroupingUsed(false);

            nf4.setMaximumFractionDigits(0);
            nf4.setMinimumFractionDigits(0);
            nf4.setMaximumIntegerDigits(4);
            nf4.setMinimumIntegerDigits(4);
            nf4.setGroupingUsed(false);

            try
            {
                aCal.setTime(aDate);

                int year = aCal.get(Calendar.YEAR);
                int month = aCal.get(Calendar.MONTH) + 1;
                int date = aCal.get(Calendar.DAY_OF_MONTH);

                return stdDate.append(nf4.format(year)).append("-").append(nf2.format(month)).append("-").append(nf2.format(date)).toString();
            }
            catch (Exception ex)
            {
                ex.printStackTrace();
            }
            finally
            {
                aCal = null;
            }
            return stdDate.toString();
        }
        return "";
    }

    private void aBtnExeSqlCommandActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aBtnExeSqlCommandActionPerformed
    {//GEN-HEADEREND:event_aBtnExeSqlCommandActionPerformed
        // ตรวจสอบรูปแบบของ Date
        String inputFromDate = this.aTxtFromDate.getText().trim();
        String inputToDate = this.aTxtToDate.getText().trim();
        this.aTxtFromDate.setText(inputFromDate);
        this.aTxtToDate.setText(inputToDate);
        if (inputFromDate.length() != 10 && inputFromDate.indexOf('-')!=-1 && inputToDate.length() != 10 && inputToDate.indexOf('-')!=-1)
        {
            this.setCursor(Cursor.getDefaultCursor());
            this.aTxtSqlPath.setEditable(true);
            this.aTxtFromDate.setEditable(true);
            this.aTxtToDate.setEditable(true);
            JOptionPane.showMessageDialog(this, ResourceBundle.getBundle("language").getString("FrmExport.aLblDate") + " " + inputFromDate + " - " + inputToDate + " incorrect format", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(this.aCmbOption.getModel().getSelectedItem().toString().toUpperCase().indexOf("SPLIT")!=-1)
        {
            Calendar runCal = Calendar.getInstance();
            runCal.setTime(getDateChristFromString(inputFromDate));

            Calendar stopCal = Calendar.getInstance();
            stopCal.setTime(getDateChristFromString(inputToDate));

            if (runCal.compareTo(stopCal) <= 0)
            {
                for (; runCal.compareTo(stopCal) <= 0;)
                {
                    // สำหรับแบบ SPLIT จะต้อง แยกออกเป็น 1 Folder = 1 วัน
                    this.execute(convertDate2StdFormat(runCal.getTime()), inputToDate);
                    
                    runCal.set(Calendar.DAY_OF_MONTH, runCal.get(Calendar.DAY_OF_MONTH) + 1);
                }
            }
            else
            {
                System.out.println("FromDate must be before ToDate.");
            }
        }
        else
        {
            this.execute(inputFromDate, inputToDate);
        }
    }//GEN-LAST:event_aBtnExeSqlCommandActionPerformed

    private void aMenuItemExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aMenuItemExitActionPerformed
    {//GEN-HEADEREND:event_aMenuItemExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_aMenuItemExitActionPerformed

    private void aMenuItemReloadFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aMenuItemReloadFileActionPerformed
    {//GEN-HEADEREND:event_aMenuItemReloadFileActionPerformed
        this.loadSqlFileFromPath();
    }//GEN-LAST:event_aMenuItemReloadFileActionPerformed

    private void aTxtToDateActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_aTxtToDateActionPerformed
    {//GEN-HEADEREND:event_aTxtToDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTxtToDateActionPerformed

    private static boolean autoRun = false;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        if(args.length>0 && "auto".equalsIgnoreCase(args[0]))
        {
            autoRun = true;
        }

        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FrmSqlServerToPg aFrmExport = new FrmSqlServerToPg();
                aFrmExport.setVisible(true);

                if(autoRun)
                {
                    aFrmExport.setExecuteDate(FrmSqlServerToPg.getCurrentDateForExecute(-1));
                    aFrmExport.execute();
                    System.exit(1);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aBtnExeSqlCommand;
    private javax.swing.JComboBox aCmbOption;
    private javax.swing.JLabel aLblFromDate;
    private javax.swing.JLabel aLblOption;
    private javax.swing.JLabel aLblSqlPath;
    private javax.swing.JLabel aLblTo;
    private javax.swing.JList aLstSqlFile;
    private javax.swing.JMenu aMenu;
    private javax.swing.JMenuBar aMenuBar;
    private javax.swing.JMenuItem aMenuItemExit;
    private javax.swing.JMenuItem aMenuItemReloadFile;
    private javax.swing.JPanel aPnlBody;
    private javax.swing.JPanel aPnlTop;
    private javax.swing.JScrollPane aScrlPaneSqlFile;
    private javax.swing.JTextField aTxtFromDate;
    private javax.swing.JTextField aTxtSqlPath;
    private javax.swing.JTextField aTxtToDate;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void setExecuteDate(String currentDateForExecute)
    {
        this.aTxtFromDate.setText(currentDateForExecute);
        this.aTxtToDate.setText(currentDateForExecute);
    }
}
